# Generated by Django 3.0.2 on 2020-01-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200129_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'mis servicios'},
        ),
    ]
